### ISSUE TITLE
Allow configuration of cache-control header (s3/digital ocean)

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/import-map-deployer#11]
See related https://github.com/openmrs/openmrs-esm-root-config/issues/5.

Browsers sometimes willfully disobey [cache-control max-age=0](https://github.com/CanopyTax/import-map-deployer/blob/master/src/io-methods/s3.js#L52). So either changing the default to 10 seconds or at least making it configurable within config.json would let users try to work around the browser's behavior.

**Comment by nhumrich** [comment]
just cause I am curious, is this all browsers? or just firefox? I get a 404 at that specific site, but I can't reproduce with latest firefox on canopy's file.

**Comment by nhumrich** [comment]
We could also try `Cache-Control: no-cache`

**Comment by joeldenning** [comment]
You get a 404 for https://openmrs-spa.org/import-map.json? I get a json file.

@jonathandick was the one who experienced the problem. It appeared (although we're not 100% sure) that he was getting an old version of the importmap.

> just cause I am curious, is this all browsers? or just firefox?

both Firefox and Chrome. If you uncheck the Disable Cache checkbox in the devtools, you stop getting the Cache-Control header. I think that means that the browser is caching the file even though the server says not to? Not 100% sure if I'm interpreting the devtools correctly. Either way, the original problem that caused this github issue is that it seemed like Jonathan was getting an old version of the import map. It could be related to Digital Ocean Spaces, instead of import-map-deployer, but I'm trying to figure out root cause.

**Comment by nhumrich** [comment]
ok, that url works now. Not sure why it wasn't before. 

Anyways, firefox is actually working correctly:

![Selection_054](https://user-images.githubusercontent.com/4661889/59065733-a359e800-886a-11e9-9f97-3b4e14c18a44.png)

it shows "cached", but you can also see the latency and header field that is because it is sending the "validate" request. The cache-control "must-revalidate", means that the browser first checks to see if the version they have is the same. If its not the same, then it gets the whole file. Its a performance optimization.

**Comment by joeldenning** [comment]
interesting. So I guess we'll just chalk the issue jonathan saw yesterday up to something we don't fully understand and can't reproduce :)
